wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
architecture:
  desc: null
  value: othello
arenaCompare:
  desc: null
  value: 40
checkpoint:
  desc: null
  value: ./temp/
cpuct:
  desc: null
  value: 1
load_folder_file:
  desc: null
  value:
  - /dev/models/8x100x50
  - best.pth.tar
load_model:
  desc: null
  value: false
maxlenOfQueue:
  desc: null
  value: 200000
numEps:
  desc: null
  value: 10
numIters:
  desc: null
  value: 20
numItersForTrainExamplesHistory:
  desc: null
  value: 20
numMCTSSims:
  desc: null
  value: 25
tempThreshold:
  desc: null
  value: 15
updateThreshold:
  desc: null
  value: 0.6
