wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
architecture:
  desc: null
  value: resnet
arenaCompare:
  desc: null
  value: 60
batch_size:
  desc: null
  value: 64
checkpoint:
  desc: null
  value: ./temp/
cpuct:
  desc: null
  value: 1
cuda:
  desc: null
  value: true
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 10
load_folder_file:
  desc: null
  value:
  - /dev/models/8x100x50
  - best.pth.tar
load_model:
  desc: null
  value: false
lr:
  desc: null
  value: 0.005
maxlenOfQueue:
  desc: null
  value: 200000
numEps:
  desc: null
  value: 30
numIters:
  desc: null
  value: 15
numItersForTrainExamplesHistory:
  desc: null
  value: 20
numMCTSSims:
  desc: null
  value: 3
num_channels:
  desc: null
  value: 512
tempThreshold:
  desc: null
  value: 15
updateThreshold:
  desc: null
  value: 0.6
